### ISSUE TITLE
Segmentation fault when running on Ubuntu Linux

### ISSUE THREAD

**Issue by Behrouz-Babaki** [cp-profiler/cp-profiler#2]
I have tried to use *cp-profiler* to visualize the search tree of *chuffed*. I first run 
```
% cp-profiler/build/cp-profiler
```
Then I run the _chuffed_ example:
```
% chuffed/build/nn_queens 5 --profiling on
```

Unfortunately, _cp-profiler_ terminates immediately, with a segmentation fault:
```
Ready to listen on: 6565
socket descriptor: 21
Segmentation fault (core dumped)

```

I have observed a similar behaviour when I tried _cp_profiler_ with _Choco_. So I guess the problem is on the _cp_profiler_ side.  I have also tried these steps on different machines (all running Ubuntu Linux). I am using the latest versions of _cp_profiler_ and _chuffed_, and the default Qt5 [package](https://packages.ubuntu.com/xenial/libs/qt5-default) from Ubuntu repositories.  

--------------------------------

To provide more information about the possible cause of the crash, I recompiled _cp_profiler_ with debug flags (`qmake CONFIG+=debug .. && make`), and repeated the previous steps. Here is the core dump analysis provided by `gdb`:

```
Reading symbols from ./cp-profiler...done.
[New LWP 2451]
[New LWP 2449]
[New LWP 2443]
[New LWP 2444]
[New LWP 2442]
[New LWP 2445]
[New LWP 2446]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./cp-profiler'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000044ab0a in cpprofiler::MessageMarshalling::deserializeString[abi:cxx11](char*&) (it=@0x7f78655fb580: 0x7f7860022000 <error: Cannot access memory at address 0x7f7860022000>)
    at ../src/cpprofiler/../cpp-integration/message.hpp:198
198	      result += *it;
[Current thread is 1 (Thread 0x7f78655fc700 (LWP 2451))]
(gdb) up
#1  0x000000000044add0 in cpprofiler::MessageMarshalling::deserialize (this=0x7f7860004370, data=0x7f7860022000 <error: Cannot access memory at address 0x7f7860022000>, size=41)
    at ../src/cpprofiler/../cpp-integration/message.hpp:318
318	        msg.set_info(deserializeString(data)); break;
(gdb) up
#2  0x0000000000449b8b in cpprofiler::ReceiverWorker::doRead (this=0x7f7860004340) at ../src/cpprofiler/receiver_worker.cpp:69
69	            marshalling.deserialize(m_buffer.data() + m_state.bytes_read, m_state.msg_size);
(gdb) up
#3  0x0000000000449803 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (cpprofiler::ReceiverWorker::*)()>::call(void (cpprofiler::ReceiverWorker::*)(), cpprofiler::ReceiverWorker*, void**) (f=(void (cpprofiler::ReceiverWorker::*)(cpprofiler::ReceiverWorker * const)) 0x449942 <cpprofiler::ReceiverWorker::doRead()>, o=0x7f7860004340, arg=0x7f78655fb880)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:501
501	            (o->*f)((*reinterpret_cast<typename RemoveRef<SignalArgs>::Type *>(arg[II+1]))...), ApplyReturnValue<R>(arg[0]);
(gdb) up
#4  0x000000000044955a in QtPrivate::FunctionPointer<void (cpprofiler::ReceiverWorker::*)()>::call<QtPrivate::List<>, void>(void (cpprofiler::ReceiverWorker::*)(), cpprofiler::ReceiverWorker*, void**) (
    f=(void (cpprofiler::ReceiverWorker::*)(cpprofiler::ReceiverWorker * const)) 0x449942 <cpprofiler::ReceiverWorker::doRead()>, o=0x7f7860004340, arg=0x7f78655fb880)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:520
520	            FunctorCall<typename Indexes<ArgumentCount>::Value, SignalArgs, R, Function>::call(f, o, arg);
(gdb) up
#5  0x00000000004493f5 in QtPrivate::QSlotObject<void (cpprofiler::ReceiverWorker::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, 
    this_=0x7f7860005a50, r=0x7f7860004340, a=0x7f78655fb880, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:143
143	                FuncType::template call<Args, R>(static_cast<QSlotObject*>(this_)->function, static_cast<typename FuncType::Object *>(r), a);
(gdb) up
#6  0x00007f788cf4dbaf in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#7  0x00007f788deb9efe in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
(gdb) up
#8  0x00007f788dec6881 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
(gdb) up
#9  0x00007f788d81205c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) up
#10 0x00007f788d817516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) up
#11 0x00007f788cf1f38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#12 0x00007f788cf75c95 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#13 0x00007f788b8f7197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) up
#14 0x00007f788b8f73f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) up
#15 0x00007f788b8f749c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) up
#16 0x00007f788cf757cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#17 0x00007f788cf1cb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#18 0x00007f788cd39834 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#19 0x000000000044846b in cpprofiler::ReceiverThread::run (this=0x1016a40) at ../src/cpprofiler/receiver_thread.cpp:57
57	    exec();
(gdb) up
#20 0x00007f788cd3e7be in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) up
#21 0x00007f788ca836ba in start_thread (arg=0x7f78655fc700) at pthread_create.c:333
333	pthread_create.c: No such file or directory.
(gdb) up
#22 0x00007f788bf1841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
109	../sysdeps/unix/sysv/linux/x86_64/clone.S: No such file or directory.
(gdb) up
Initial frame selected; you cannot go up.
```

**Comment by alberthendriks** [comment]
Same here with Choco on Debian

**Comment by PseudoProgrammer** [comment]
same here with ubuntu
